image: node:6.12

cache:
  paths:
  - node_modules/

stages:
  - test

run_tests:
  stage: test
  script:
    - env
    - export NODE_ENV=development
    - curl -s -o $(pwd)/cvrg https://raw.githubusercontent.com/cvrg-report/cvrg/master/cvrg && chmod +x $(pwd)/cvrg
    - npm install
    - npm run test
    - npm run coverage
