image: node:6.12

cache:
  paths:
  - node_modules/

stages:
  - test

run_tests:
  stage: test
  script:
   - env
   - curl -s -o $(pwd)/cvrg.sh https://gist.githubusercontent.com/tobilg/b0fae1eacb844bbbbe96c495347ab498/raw/dd30d59b875e7918d33dbec2d43903749578fedf/cvrg.sh && chmod +x $(pwd)/cvrg.sh
   - export NODE_ENV=development
   - npm install
   - npm run test

run_coverage:
  stage: test
  script:
   - npm run coverage
