image: node:6.12

cache:
  paths:
  - node_modules/

stages:
  - test

run_tests:
  stage: test
  script:
    - env
    - export NODE_ENV=development
    - curl -s -o $(pwd)/cvrg https://cvrg.report/bash && chmod +x $(pwd)/cvrg
    - npm install
    - npm run test
    - npm run coverage-from-stdin
    - npm run coverage-from-reports
