image: node:6.12

cache:
  paths:
  - node_modules/

stages:
  - test

run_tests:
  stage: test
  script:
    - env
    - export NODE_ENV=development
    - curl -s -o $(pwd)/cvrg.sh https://gist.githubusercontent.com/tobilg/b0fae1eacb844bbbbe96c495347ab498/raw/65f01c38ef2c97c0060cc37ac52b51205d35c8c7/cvrg.sh && chmod +x $(pwd)/cvrg.sh
    - npm install
    - npm run test
    - npm run coverage
