language: node_js

env:
  - NODE_ENV=development

before_script:
  - env
  - curl -s -o $(pwd)/cvrg.sh https://gist.githubusercontent.com/tobilg/b0fae1eacb844bbbbe96c495347ab498/raw/dd30d59b875e7918d33dbec2d43903749578fedf/cvrg.sh && chmod +x $(pwd)/cvrg.sh

node_js:
  - '6'

install:
  - "npm i"

script:
  - "npm run test"

after_script:
  - "npm run coverage"
