language: node_js

node_js:
  - "6"

install:
  - "npm i"

before_script:
  - curl -s -o $(pwd)/cvrg.sh https://gist.githubusercontent.com/tobilg/b0fae1eacb844bbbbe96c495347ab498/raw/80c5ae15c36d5f1d9392665ed5273425f98223ef/cvrg.sh && chmod +x $(pwd)/cvrg.sh

script:
  - "npm run test"

after_script
  - "npm run coverage"

