language: node_js

env:
  - NODE_ENV=development

before_script:
  - env
  - curl -s -L -o $(pwd)/cvrg https://cvrg.report/bash && chmod +x $(pwd)/cvrg

node_js:
  - '6'

install:
  - "npm i"

script:
  - "npm run test"

after_script:
  - "npm run coverage-from-stdin"
  - "npm run coverage-from-reports"
