language: node_js

env:
  - NODE_ENV=development

before_script:
  - env
  - curl -s -o $(pwd)/cvrg https://raw.githubusercontent.com/cvrg-report/cvrg/master/cvrg && chmod +x $(pwd)/cvrg

node_js:
  - '6'

install:
  - "npm i"

script:
  - "npm run test"

after_script:
  - "npm run coverage"
